defmodule Textbin.Storage do
  @moduledoc """
  Stores paste bodies independently from their database metadata.

  Storage keys are generated by Textbin and are intentionally opaque to callers.
  This keeps database records portable between filesystem and object-storage
  adapters.
  """

  @type metadata :: %{size_bytes: non_neg_integer(), sha256: binary()}

  @callback put(String.t(), binary(), keyword()) :: {:ok, metadata()} | {:error, term()}
  @callback get(String.t(), keyword()) :: {:ok, binary()} | {:error, term()}
  @callback delete(String.t(), keyword()) :: :ok | {:error, term()}

  def put(storage_key, data) when is_binary(storage_key) and is_binary(data) do
    {adapter, opts} = adapter_and_opts()
    adapter.put(storage_key, data, opts)
  end

  def get(storage_key) when is_binary(storage_key) do
    {adapter, opts} = adapter_and_opts()
    adapter.get(storage_key, opts)
  end

  def get!(storage_key) when is_binary(storage_key) do
    case get(storage_key) do
      {:ok, data} -> data
      {:error, reason} -> raise "could not read stored paste content: #{inspect(reason)}"
    end
  end

  def delete(storage_key) when is_binary(storage_key) do
    {adapter, opts} = adapter_and_opts()
    adapter.delete(storage_key, opts)
  end

  def child_spec do
    {adapter, opts} = adapter_and_opts()

    if Code.ensure_loaded?(adapter) and function_exported?(adapter, :child_spec, 1) do
      adapter.child_spec(opts)
    end
  end

  defp adapter_and_opts do
    config = Application.fetch_env!(:textbin, __MODULE__)
    {Keyword.fetch!(config, :adapter), Keyword.get(config, :opts, [])}
  end
end
