defmodule Textbin.Storage do
  @moduledoc """
  Stores paste bodies independently from their database metadata.

  Storage keys are generated by Textbin and are intentionally opaque to callers.
  This keeps database records portable between filesystem and object-storage
  adapters.
  """

  @type metadata :: %{size_bytes: non_neg_integer(), sha256: binary()}

  @callback put(String.t(), binary(), keyword()) :: {:ok, metadata()} | {:error, term()}
  @callback put_file(String.t(), Path.t(), metadata(), keyword()) ::
              {:ok, metadata()} | {:error, term()}
  @callback get(String.t(), keyword()) :: {:ok, binary()} | {:error, term()}
  @callback delete(String.t(), keyword()) :: :ok | {:error, term()}

  def put(storage_key, data) when is_binary(storage_key) and is_binary(data) do
    {adapter, opts} = adapter_and_opts()
    adapter.put(storage_key, data, opts)
  end

  def put_file(storage_key, path, metadata)
      when is_binary(storage_key) and is_binary(path) and is_map(metadata) do
    {adapter, opts} = adapter_and_opts()
    adapter.put_file(storage_key, path, metadata, opts)
  end

  def calculate_metadata(chunks) do
    {size_bytes, hash} =
      Enum.reduce(chunks, {0, :crypto.hash_init(:sha256)}, fn chunk, {size_bytes, hash} ->
        {size_bytes + byte_size(chunk), :crypto.hash_update(hash, chunk)}
      end)

    %{size_bytes: size_bytes, sha256: :crypto.hash_final(hash)}
  end

  def get(storage_key) when is_binary(storage_key) do
    {adapter, opts} = adapter_and_opts()
    adapter.get(storage_key, opts)
  end

  def get!(storage_key) when is_binary(storage_key) do
    case get(storage_key) do
      {:ok, data} -> data
      {:error, reason} -> raise "could not read stored paste content: #{inspect(reason)}"
    end
  end

  def delete(storage_key) when is_binary(storage_key) do
    {adapter, opts} = adapter_and_opts()
    adapter.delete(storage_key, opts)
  end

  def child_spec do
    {adapter, opts} = adapter_and_opts()

    if Code.ensure_loaded?(adapter) and function_exported?(adapter, :child_spec, 1) do
      adapter.child_spec(opts)
    end
  end

  defp adapter_and_opts do
    config = Application.fetch_env!(:textbin, __MODULE__)

    opts =
      case Keyword.get(config, :opts, []) do
        {:replace, opts} -> opts
        opts -> opts
      end

    {Keyword.fetch!(config, :adapter), opts}
  end
end
